version: '3'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
  python:
    image: python:3.10-slim
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: /bin/bash